# -*- mode: ruby -*-
# vi: set ft=ruby :

require "rbconfig"

open(".env", "r").readlines.each {
  |l|
  kv = l.split("=")
  if kv[1] != nil
    ENV[kv[0]] = kv[1].strip
  end
}

HOST_CPU = RbConfig::CONFIG["host_cpu"]
HOST_OS = RbConfig::CONFIG["host_os"]
APPLE_SILICON = HOST_OS.include?("darwin") && ["arm64", "aarch64"].include?(HOST_CPU)
VM_BOX = ENV["STACK_BOX"] || (APPLE_SILICON ? "bento/ubuntu-22.04" : "generic/ubuntu2204")
ARM_MACHINE_HYPERVISOR_IP = ENV["ARM_MACHINE_HYPERVISOR_IP"] || "192.168.56.100"
ARM_MACHINE_HYPERVISOR_NET = ENV["ARM_MACHINE_HYPERVISOR_NET"] || "192.168.56.0/24"

LIBVIRT_HOST_IP = ENV["LIBVIRT_HOST_IP"] || "192.168.56.1"
PROVISIONER_IP = ENV["PROVISIONER_IP"] || "192.168.56.4"
LOADBALANCER_IP = ENV["LOADBALANCER_IP"] || "192.168.56.40"
LOADBALANCER_IP_2 = ENV["LOADBALANCER_IP_2"] || "192.168.56.41"
GATEWAY_IP = ENV["GATEWAY_IP"] || ""
# Overwrite GATEWAY_IP on Apple ARM to ARM_MACHINE_HYPERVISOR_IP if it's not set
GATEWAY_IP = if APPLE_SILICON && GATEWAY_IP.empty?
    ARM_MACHINE_HYPERVISOR_IP
  else
    GATEWAY_IP
  end
MACHINE1_IP = ENV["MACHINE1_IP"] || "192.168.56.43"
MACHINE1_MAC = (ENV["MACHINE1_MAC"] || "08:00:27:9E:F5:3A").downcase
HELM_CHART_VERSION = ENV["HELM_CHART_VERSION"] || "0.19.1"
KUBECTL_VERSION = ENV["KUBECTL_VERSION"] || "1.28.3"
K3D_VERSION = ENV["K3D_VERSION"] || "v5.6.0"
HELM_VERSION = ENV["HELM_VERSION"] || "v3.14.4"
HELM_LOADBALANCER_INTERFACE = ENV["HELM_LOADBALANCER_INTERFACE"] || "eth1"
DEST_DIR_BASE = "/playground/stack/"

Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |libvirt|
    libvirt.qemu_use_session = false
  end

  config.vm.define "stack" do |stack|
    stack.vm.hostname = "stack"

    stack.vm.box = VM_BOX
    stack.vm.synced_folder "", DEST_DIR_BASE
    stack.vm.network "private_network", ip: "192.168.56.4", netmask: "255.255.255.0",
                                        libvirt__network_name: "tink_network",
                                        libvirt__host_ip: LIBVIRT_HOST_IP,
                                        libvirt__netmask: "255.255.255.0",
                                        libvirt__dhcp_enabled: false

    stack.vm.provider "virtualbox" do |v, override|
      v.memory = 2048
      v.cpus = 2
    end

    stack.vm.provider "libvirt" do |l, override|
      l.memory = 2048
      l.cpus = 2
      override.vm.synced_folder "", DEST_DIR_BASE, type: "rsync"
    end

    stack.vm.provision :shell, path: "setup.sh", args: [PROVISIONER_IP, MACHINE1_IP, MACHINE1_MAC, DEST_DIR_BASE, LOADBALANCER_IP, HELM_CHART_VERSION, HELM_LOADBALANCER_INTERFACE, KUBECTL_VERSION, K3D_VERSION, HELM_VERSION, LOADBALANCER_IP_2, GATEWAY_IP]
  end

  config.vm.define :machine1, autostart: false do |machine1|
    machine1.ssh.insert_key = false
    machine1.vm.boot_timeout = 10
    machine1.vm.synced_folder ".", "/vagrant", disabled: true
    machine1.vm.network :private_network, ip: MACHINE1_IP,
                                          mac: MACHINE1_MAC.gsub(/[:-]/, "").strip,
                                          adapter: 1,
                                          libvirt__network_name: "tink_network",
                                          libvirt__dhcp_enabled: false,
                                          libvirt__forward_mode: "nat"

    machine1.vm.provider "libvirt" do |v|
      v.storage :file, :size => "20G"
      v.memory = 4096
      v.cpus = 2
      v.boot "hd"
      v.boot "network"
      v.graphics_ip = "0.0.0.0"
      v.machine_arch = "x86_64"
    end

    machine1.vm.provider "virtualbox" do |v, override|
      override.vm.box = "jtyr/pxe"
      v.memory = 2048
      v.cpus = 2
      v.gui = true
      v.customize ["modifyvm", :id, "--nic1", "hostonlynet", "--nic2", "nat", "--boot1", "disk", "--boot2", "net"]
      v.customize ["modifyvm", :id, "--macaddress1", MACHINE1_MAC.gsub(/[:-]/, "").strip]
      v.customize ["setextradata", :id, "GUI/ScaleFactor", "3.0"]
      v.check_guest_additions = false
    end
  end

  config.vm.define "arm_machine1", autostart: false do |arm_machine1|
    arm_machine1.vm.synced_folder ".", "/vagrant", disabled: true
    arm_machine1.vm.network "private_network", ip: ARM_MACHINE_HYPERVISOR_IP
    arm_machine1.vm.hostname = "arm-machine1"

    arm_machine1.vm.provider "virtualbox" do |v, override|
      override.vm.box = VM_BOX
      v.memory = 2048
      v.cpus = 2
      v.gui = false

      arm_machine1.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y bridge-utils qemu-system-aarch64

        sudo ip link add name br0 type bridge || true
        sudo ip link set eth1 master br0
        sudo ip addr flush dev eth1
        sudo ip link set eth1 up
        sudo ip link set br0 up
        sudo ip a add #{ARM_MACHINE_HYPERVISOR_IP}/24 dev br0 || true

        sudo mkdir -p /etc/qemu
        printf 'allow %s\n' "br0" | sudo tee /etc/qemu/bridge.conf >/dev/null
        sudo chown root:root /etc/qemu/bridge.conf
        sudo chmod 0640 /etc/qemu/bridge.conf

        sudo sysctl -w net.ipv4.ip_forward=1
        echo 'net.ipv4.ip_forward=1' | sudo tee /etc/sysctl.d/99-ipforward.conf

        sudo iptables -t nat -A POSTROUTING -s #{ARM_MACHINE_HYPERVISOR_NET} -o eth0 -j MASQUERADE
        sudo iptables -A FORWARD -i br0 -o eth0 -j ACCEPT
        sudo iptables -A FORWARD -i eth0 -o br0 -m state --state RELATED,ESTABLISHED -j ACCEPT
        SHELL
    end
  end
end
