# -*- mode: ruby -*-
# vi: set ft=ruby :

open(".env", "r").readlines.each {
  |l|
  kv = l.split("=")
  if kv[1] != nil
    ENV[kv[0]] = kv[1].strip
  end
}

LIBVIRT_HOST_IP = ENV["LIBVIRT_HOST_IP"] || "192.168.56.1"
PROVISIONER_IP = ENV["PROVISIONER_IP"] || "192.168.56.4"
LOADBALANCER_IP = ENV["LOADBALANCER_IP"] || "192.168.56.4"
MACHINE1_IP = ENV["MACHINE1_IP"] || "192.168.56.43"
MACHINE1_MAC = (ENV["MACHINE1_MAC"] || "08:00:27:9E:F5:3A").downcase
USE_HELM = ENV["USE_HELM"] || ""
HELM_CHART_VERSION = ENV["HELM_CHART_VERSION"] || "0.1.2"
HELM_LOADBALANCER_INTERFACE = ENV["HELM_LOADBALANCER_INTERFACE"] || "eth1"
STACK_OPT = "compose/"
STACK_BASE_DIR = "../../stack/"
STACK_DIR = STACK_BASE_DIR + STACK_OPT
DEST_DIR_BASE = "/sandbox/stack/"
DEST_DIR = DEST_DIR_BASE + STACK_OPT
ENV_FILE = ".env_compose"

Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |libvirt|
    libvirt.qemu_use_session = false
  end

  config.vm.define "provisioner" do |provisioner|
    if USE_HELM == "true"
      STACK_DIR = STACK_BASE_DIR + "helm/"
      DEST_DIR = DEST_DIR_BASE + "helm/"
    end
    provisioner.vm.box = "generic/ubuntu2204"
    provisioner.vm.synced_folder STACK_BASE_DIR, DEST_DIR_BASE
    provisioner.vm.network "private_network", ip: "192.168.56.4", netmask: "255.255.255.0",
                                              libvirt__network_name: "tink_network",
                                              libvirt__host_ip: LIBVIRT_HOST_IP,
                                              libvirt__netmask: "255.255.255.0",
                                              libvirt__dhcp_enabled: false

    provisioner.vm.provider "virtualbox" do |v, override|
      v.memory = 2048
      v.cpus = 2
      override.vm.synced_folder STACK_BASE_DIR, DEST_DIR_BASE
    end

    provisioner.vm.provider "libvirt" do |l, override|
      l.memory = 2048
      l.cpus = 2
      override.vm.synced_folder STACK_BASE_DIR, DEST_DIR_BASE, type: "rsync"
    end

    if USE_HELM == "true"
      provisioner.vm.provision :shell, path: STACK_DIR + "/setup.sh", args: [PROVISIONER_IP, MACHINE1_IP, MACHINE1_MAC, DEST_DIR, LOADBALANCER_IP, HELM_CHART_VERSION, HELM_LOADBALANCER_INTERFACE]
    else
      provisioner.vm.provision "file", source: ENV_FILE, destination: DEST_DIR + ".env"  
      provisioner.vm.provision :shell, path: STACK_DIR + "/setup.sh"
    end
  end

  config.vm.define :machine1, autostart: false do |machine1|
    machine1.ssh.insert_key = false
    machine1.vm.boot_timeout = 10
    machine1.vm.synced_folder ".", "/vagrant", disabled: true
    machine1.vm.network :private_network, ip: MACHINE1_IP,
                                          mac: MACHINE1_MAC.gsub(/[:-]/, "").strip,
                                          adapter: 1,
                                          libvirt__network_name: "tink_network",
                                          libvirt__dhcp_enabled: false,
                                          libvirt__forward_mode: "nat"

    machine1.vm.provider "libvirt" do |v|
      v.storage :file, :size => "20G"
      v.memory = 4096
      v.cpus = 2
      v.boot "hd"
      v.boot "network"
      v.graphics_ip = "0.0.0.0"
      v.machine_arch = "x86_64"
    end

    machine1.vm.provider "virtualbox" do |v, override|
      override.vm.box = "jtyr/pxe"
      v.memory = 2048
      v.cpus = 2
      v.gui = true
      v.customize ["modifyvm", :id, "--nic1", "hostonly", "--nic2", "nat", "--boot1", "disk", "--boot2", "net"]
      v.customize ["setextradata", :id, "GUI/ScaleFactor", "3.0"]
      v.check_guest_additions = false
    end
  end
end
