---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            {
              "interface": "net1",
              "ips": [
                "192.168.1.2/29"
              ],
              "name": "tink",
              "namespace": "default"
            }
          ]
      labels:
        app: nginx
    spec:
      containers:
        - image: docker.io/nginx:alpine
          imagePullPolicy: Always
          name: nginx
          ports:
            - containerPort: 80
              hostPort: 8080
              name: http
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: nginx-data
      restartPolicy: Always
      volumes:
        - name: nginx-data
          persistentVolumeClaim:
            claimName: nginx-data
        - name: source-certs
          secret:
            secretName: certs
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: nginx
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nginx
  name: nginx-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
